Capstone
Thi-Ponce/Capstone-Project-1 pull request #1
Opened 2022-02-02 19:31 UTC by Thi-Ponce

### Capstone project:
- Create a simple webpage with a home and about page;
- Make sure it works for mobile (up to 768px);
- Make sure it works for desktop (base screen used 1262px);
- Loom link for the presentation: https://www.loom.com/share/37c8786a067349ee940345752908de6a

2022-02-02 20:11 UTC, Rustamxon7 requested changes
Hi @Thi-Ponce , 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯
- Dry code 💯
- Design is beautiful ✔


There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 20:11 UTC, rustam-tolipov commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/thiago-ponce)
## Good job so far 🙌

- [x] First of all, thank you for the great video presentation, it made it easy to review your code, don't forget to add Add descriptive README files to your project. Please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

2022-02-02 20:11 UTC, rustam-tolipov commented on about.html
> +				</nav>
## Let's start improving your design 😉

- [x] There is one thing in your navigation that is missing. You forgot to add the black part at the top of the navigation which contains some links 🔗. Please kinds add that part and don't forget to hide it in the mobile version also
- [x] [OPTIONAL] Its optional but highly recommended. You are using tab size `8` but I suggest using `2`. Currently, it's making your code kinda bad looking and hard to read 👌

**Your design**
![image](https://user-images.githubusercontent.com/69011963/152227972-3aa9c817-b11f-40af-86f0-da714a1c3f91.png)

**Original design** 
![image](https://user-images.githubusercontent.com/69011963/152228114-21d1dc99-59c4-4420-b5b1-4a8004887477.png)

2022-02-02 20:11 UTC, rustam-tolipov commented on index.html
> +	</section>
- [x] One thing is missing here is your footer. Let's copy the footer from about.html add here 📁

**Screenshot**
![image](https://user-images.githubusercontent.com/69011963/152229247-1005d19f-5270-40b8-a351-242769a468af.png)

2022-02-02 20:11 UTC, Rustamxon7 commented on styles/about-style.css
> +}
### I like your animation 😀. Keep on creating such great websites. Happy coding ☕

2022-02-02 23:06 UTC, andersonlebon requested changes
## Hi @Thi-Ponce 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 23:06 UTC, andersonlebon commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/thiago-ponce)
- [ ] As the previous reviewer said don't forget to add Add descriptive README files to your project. Please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it with your project information. Kindly add some important sections in your Readme file like: ` Contributing`, `Acknowledgments`, ` License`, `Live Demo (if available)`, `Getting Started` referring yourself to [this template](https://github.com/microverseinc/readme-template).

2022-02-03 14:51 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @Thi-Ponce 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional Changes ♻️ 

- [ ] The page styles are currently not loading in project, this issue may be because of the forward slash that is placed before the file name as seen here 👉🏻 `<link rel="stylesheet" href="/styles/about-style.css">`
- [ ] Another point is that the link to the live project is missing in the README. Please include it to allow users to have a feel of your project without looking through the code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 15:09 UTC, merged